# Generated by Django 3.0.6 on 2020-06-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_createcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcourse',
            name='language',
            field=models.CharField(default='Hindi + English', max_length=50),
        ),
        migrations.AddField(
            model_name='createcourse',
            name='pricing',
            field=models.CharField(default='149', max_length=10),
        ),
    ]
