# Generated by Django 3.0.6 on 2020-06-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200619_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddVedios',
        ),
    ]
