# Generated by Django 3.0.6 on 2020-06-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_addvedios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createCourse',
        ),
    ]
