# Generated by Django 3.0.6 on 2020-06-20 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_delete_createcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='createCourse',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=150)),
                ('sub_category', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('language', models.CharField(default='Hindi + English', max_length=50)),
                ('pricing', models.CharField(default='149', max_length=10)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('creater', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
