# Generated by Django 3.0.6 on 2020-06-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_createcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcourse',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='createcourse',
            name='sub_category',
            field=models.CharField(max_length=50),
        ),
    ]
