# Generated by Django 3.0.6 on 2020-06-20 07:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_auto_20200620_0704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='createCourse',
            new_name='Courses',
        ),
    ]
