# Generated by Django 3.0.6 on 2020-06-23 10:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_vedios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vedios',
            new_name='Videos',
        ),
    ]
