# Generated by Django 3.0.6 on 2020-06-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200623_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='resource',
            field=models.FileField(null=True, upload_to='home/resource', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='home/image'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='videofile',
            field=models.FileField(null=True, upload_to='home/video', verbose_name=''),
        ),
    ]
