# Generated by Django 3.0.6 on 2020-06-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200623_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courseThumbnail',
            field=models.ImageField(default='', upload_to='home/courseThumbnail'),
        ),
    ]
