# Generated by Django 3.0.6 on 2020-06-25 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_courses_creater_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Courses')),
            ],
        ),
    ]
