# Generated by Django 3.0.6 on 2020-06-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_courses_varified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='varified',
            new_name='verified',
        ),
    ]
