# Generated by Django 3.0.6 on 2020-07-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='discription',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='courses',
            name='enrolled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
