# Generated by Django 3.0.6 on 2020-07-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20200701_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='ratedBy',
            field=models.IntegerField(default=0),
        ),
    ]
