# Generated by Django 3.0.6 on 2020-07-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_mycources'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyCources',
            new_name='MyCourses',
        ),
    ]
