# Generated by Django 3.0.6 on 2020-07-05 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0025_mycourses_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedVideos',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watched', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Videos')),
            ],
        ),
    ]
