# Generated by Django 3.0.6 on 2020-07-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='answered',
            field=models.CharField(default='False', max_length=50),
        ),
    ]
