# Generated by Django 3.0.6 on 2020-07-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedvideos',
            name='creater',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
