# Generated by Django 3.0.6 on 2020-07-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_watchedvideos_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedvideos',
            name='creater',
            field=models.IntegerField(default=0),
        ),
    ]
