# Generated by Django 3.0.6 on 2020-07-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20200712_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedvideos',
            name='watched',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Videos'),
        ),
    ]
