# Generated by Django 3.0.6 on 2020-07-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20200712_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='sub_category2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
