# Generated by Django 3.0.6 on 2020-07-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_hometutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometutor',
            name='id_proof',
            field=models.FileField(null=True, upload_to='home/homeTutor', verbose_name=''),
        ),
    ]
