# Generated by Django 3.0.6 on 2020-07-20 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0037_hometutor_id_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTutorDemo',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('pin', models.IntegerField()),
                ('address2', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('homeTutor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.HomeTutor')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
