# Generated by Django 3.0.6 on 2020-07-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_hometutor_unlocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometutordemo',
            name='homeTutor',
            field=models.IntegerField(),
        ),
    ]
