# Generated by Django 3.0.6 on 2020-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_reviewcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcourse',
            name='username',
            field=models.CharField(default='', max_length=500),
        ),
    ]
