# Generated by Django 3.0.6 on 2020-07-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_reviewcourse_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=20)),
                ('message', models.TextField(default='')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
