# Generated by Django 3.0.6 on 2020-07-24 10:38

from django.db import migrations, models
import home.validaters


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='resource',
            field=models.FileField(null=True, upload_to='home/resource', validators=[home.validaters.file_size], verbose_name=''),
        ),
    ]
