# Generated by Django 3.0.6 on 2020-07-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='home/image', verbose_name=''),
        ),
    ]
