# Generated by Django 3.0.6 on 2020-07-24 11:02

from django.db import migrations
import home.validaters


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20200724_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='resource',
            field=home.validaters.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='home/resource'),
        ),
    ]
