# Generated by Django 3.0.6 on 2020-07-27 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0047_auto_20200726_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestVideo',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('videofile', models.FileField(null=True, upload_to='home/video', verbose_name='')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
