# Generated by Django 3.0.6 on 2020-07-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_testvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testvideo',
            name='videofile',
            field=models.FileField(null=True, upload_to='home/testvideo', verbose_name=''),
        ),
    ]
