# Generated by Django 3.0.6 on 2020-08-12 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0049_auto_20200727_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('upi', models.CharField(default='', max_length=40)),
                ('acc', models.CharField(default='', max_length=40)),
                ('ifsc', models.CharField(default='', max_length=40)),
                ('account_holder', models.CharField(default='', max_length=40)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
