# Generated by Django 3.0.6 on 2020-08-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_accountdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometutor',
            name='registered_for',
            field=models.CharField(default='Home Tutor', max_length=20),
        ),
    ]
