# Generated by Django 3.0.6 on 2020-08-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_hometutor_registered_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometutordemo',
            name='reg_for',
            field=models.CharField(default='Home Tutor', max_length=200),
        ),
    ]
