# Generated by Django 3.0.6 on 2020-08-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_hometutordemo_reg_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometutordemo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
