# Generated by Django 3.0.6 on 2020-08-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_hometutordemo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometutor',
            old_name='unlocked',
            new_name='unlockedHT',
        ),
        migrations.AddField(
            model_name='hometutor',
            name='unlockedON',
            field=models.IntegerField(default=0),
        ),
    ]
