# Generated by Django 3.0.6 on 2020-08-16 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0054_auto_20200816_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometutordemo',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hometutordemo',
            name='address2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hometutordemo',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RequestTution',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('reg_for', models.CharField(default='Home Tutor', max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('pin', models.IntegerField(default=0)),
                ('address2', models.CharField(default='', max_length=200)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
