# Generated by Django 3.0.6 on 2020-09-24 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0057_auto_20200816_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('sub_category2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=1000)),
                ('question', models.CharField(default='', max_length=1000000)),
                ('answer', models.CharField(default='', max_length=1000000)),
                ('correct', models.CharField(default='', max_length=1000000)),
                ('creater', models.CharField(default='', max_length=100)),
                ('instructions', models.CharField(default='', max_length=10000)),
                ('Time', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('useranswer', models.CharField(default='', max_length=1000000)),
                ('correct', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Test')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.FileField(blank=True, upload_to='home/testimage', verbose_name='')),
                ('option1', models.FileField(blank=True, upload_to='home/testimage', verbose_name='')),
                ('option2', models.FileField(blank=True, upload_to='home/testimage', verbose_name='')),
                ('option3', models.FileField(blank=True, upload_to='home/testimage', verbose_name='')),
                ('option4', models.FileField(blank=True, upload_to='home/testimage', verbose_name='')),
                ('option5', models.FileField(blank=True, upload_to='home/testimage', verbose_name='')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestCart',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Test')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyTest',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default=-1)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Test')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
