# Generated by Django 3.0.6 on 2020-09-26 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0060_auto_20200925_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('sub_category2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAddedTest',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=1000)),
                ('price', models.CharField(default='', max_length=1000)),
                ('testfile', models.FileField(null=True, upload_to='home/quize', verbose_name='')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
