# Generated by Django 3.0.6 on 2020-09-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_instructoraddedtest_testcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='isFree',
            field=models.BooleanField(default=False),
        ),
    ]
