# Generated by Django 3.0.6 on 2020-10-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_videos_isfree'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='duration',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videos',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='home/resource', verbose_name=''),
        ),
    ]
