# Generated by Django 3.0.6 on 2020-10-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_auto_20201002_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
