# Generated by Django 3.0.6 on 2020-10-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_auto_20201002_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='share',
            field=models.IntegerField(default=70),
        ),
    ]
