# Generated by Django 3.0.6 on 2020-10-06 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0066_teachcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubtReply',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('liked', models.BooleanField(default=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('doubt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Test')),
                ('parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.DoubtReply')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('doubtfile', models.FileField(blank=True, upload_to='home/doubt', verbose_name='')),
                ('doubttext', models.CharField(default='', max_length=10000)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
