# Generated by Django 3.0.6 on 2020-10-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_doubt_doubtreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
    ]
