# Generated by Django 3.0.6 on 2020-10-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_doubt_likecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='username',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
