# Generated by Django 3.0.6 on 2020-10-08 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0069_doubt_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doubtliked',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('doubt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Doubt')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
