# Generated by Django 3.0.6 on 2020-10-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_doubtliked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubtreply',
            name='doubt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Doubt'),
        ),
    ]
