# Generated by Django 3.0.6 on 2020-10-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_doubtreply_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=1000)),
                ('disc', models.CharField(default='', max_length=1000)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
