# Generated by Django 3.0.6 on 2020-10-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='image',
            field=models.FileField(null=True, upload_to='home/DUpdates', verbose_name=''),
        ),
    ]
