# Generated by Django 3.0.6 on 2020-10-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_updates_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='disc',
            field=models.TextField(),
        ),
    ]
