# Generated by Django 3.0.6 on 2020-10-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_auto_20201011_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='discHindi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='updates',
            name='titleHindi',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='disc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='title',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
