# Generated by Django 3.0.6 on 2020-10-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_bookmark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubtreply',
            name='doubtfile',
            field=models.FileField(blank=True, upload_to='home/doubt', verbose_name=''),
        ),
    ]
