# Generated by Django 3.0.6 on 2020-10-17 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0084_doubtreply_doubtfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SratchCard',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('deviceId', models.CharField(default='', max_length=1000)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('scard', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.SratchCard')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
