# Generated by Django 3.0.6 on 2020-10-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_sratchcard_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='wallet',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
