# Generated by Django 3.0.6 on 2020-10-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_auto_20201018_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='scard',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='status',
        ),
        migrations.AddField(
            model_name='sratchcard',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='cardtype',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='wallet',
            name='remaining',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
