# Generated by Django 3.0.6 on 2020-10-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_auto_20201018_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='sratchcard',
            name='amount',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
