# Generated by Django 3.0.6 on 2020-10-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_sratchcard_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='cardtype',
        ),
        migrations.AddField(
            model_name='sratchcard',
            name='cardtype',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
