# Generated by Django 3.0.6 on 2020-10-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_auto_20201020_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='report',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
