# Generated by Django 3.0.6 on 2020-10-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_doubt_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
