# Generated by Django 3.0.6 on 2020-10-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_auto_20201023_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doubt',
            old_name='report',
            new_name='reports',
        ),
    ]
