# Generated by Django 3.0.6 on 2020-10-26 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0092_auto_20201023_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Megaquiz',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='', max_length=1000000)),
                ('option', models.CharField(default='', max_length=1000000)),
                ('correct', models.CharField(default='', max_length=1000000)),
                ('time', models.CharField(default='', max_length=100000)),
                ('winner1name', models.CharField(blank=True, default='', max_length=100)),
                ('winner2name', models.CharField(blank=True, default='', max_length=100)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('winner1', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner1_users', to=settings.AUTH_USER_MODEL)),
                ('winner2', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner2_users', to=settings.AUTH_USER_MODEL)),
                ('winner3', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner3_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
