# Generated by Django 3.0.6 on 2020-10-26 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0094_megaquiz_winner3name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megaquiz',
            name='winner1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner1_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='megaquiz',
            name='winner1name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='megaquiz',
            name='winner2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner2_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='megaquiz',
            name='winner2name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='megaquiz',
            name='winner3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner3_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='megaquiz',
            name='winner3name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
