# Generated by Django 3.0.6 on 2020-10-26 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_auto_20201026_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubtreply',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
