# Generated by Django 3.0.6 on 2020-10-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_megaquizeinstruction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MegaQuizeInstruction',
            new_name='MegaQuizInstruction',
        ),
    ]
