# Generated by Django 3.0.6 on 2020-10-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_auto_20201027_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaquiz',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
