# Generated by Django 3.0.6 on 2020-10-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_megaquiz_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('link', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
