# Generated by Django 3.0.6 on 2020-11-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_accountdetailsformq'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubtreply',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
