# Generated by Django 3.0.6 on 2020-11-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0103_doubtreply_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaquiz',
            name='optionHindi',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AddField(
            model_name='megaquiz',
            name='questionHindi',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
