# Generated by Django 3.0.6 on 2020-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0104_auto_20201103_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megaquiz',
            name='option',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='megaquiz',
            name='optionHindi',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='megaquiz',
            name='question',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='megaquiz',
            name='questionHindi',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
    ]
