# Generated by Django 3.0.6 on 2020-11-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0105_auto_20201103_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='megaquizinstruction',
            old_name='delay',
            new_name='min',
        ),
        migrations.AddField(
            model_name='megaquizinstruction',
            name='hrs',
            field=models.IntegerField(default=20),
        ),
    ]
