# Generated by Django 3.0.6 on 2020-11-05 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0106_auto_20201105_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaquizResult',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('mq', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Megaquiz')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
