# Generated by Django 3.0.6 on 2020-11-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0107_megaquizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaquizresult',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
