# Generated by Django 3.0.6 on 2020-11-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_megaquizresult_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='courses',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
    ]
