# Generated by Django 3.0.6 on 2020-11-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0109_test_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='isFree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
    ]
