# Generated by Django 3.0.6 on 2020-11-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0111_generalnotify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=1000, null=True)),
                ('language', models.CharField(default='', max_length=100, null=True)),
                ('category', models.CharField(default='', max_length=500, null=True)),
                ('doubtfile', models.FileField(blank=True, upload_to='home/notes', verbose_name='')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
