# Generated by Django 3.0.6 on 2020-11-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0112_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='doubtfile',
            new_name='file',
        ),
    ]
