# Generated by Django 3.0.6 on 2020-12-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0118_feed_captions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordoftheDay',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(default=0, max_length=1000)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
