# Generated by Django 3.0.6 on 2020-12-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0120_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='category',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
