# Generated by Django 3.0.6 on 2020-12-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0123_auto_20201228_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='isVideo',
            field=models.BooleanField(default=False),
        ),
    ]
