# Generated by Django 3.0.6 on 2020-12-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0124_feed_isvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeEnglish',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('questionImage', models.FileField(blank=True, null=True, upload_to='home/practice', verbose_name='')),
                ('option1', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option1img', models.FileField(blank=True, null=True, upload_to='home/practice', verbose_name='')),
                ('option2', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option2img', models.FileField(blank=True, null=True, upload_to='home/practice', verbose_name='')),
                ('option3', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option3img', models.FileField(blank=True, null=True, upload_to='home/practice', verbose_name='')),
                ('option4', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option4img', models.FileField(blank=True, null=True, upload_to='home/practice', verbose_name='')),
                ('option5', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option5img', models.FileField(blank=True, null=True, upload_to='home/practice', verbose_name='')),
                ('correct', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
