# Generated by Django 3.0.6 on 2020-12-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0125_practiceenglish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practiceenglish',
            old_name='question',
            new_name='quetion',
        ),
    ]
