# Generated by Django 3.0.6 on 2020-12-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0128_auto_20201230_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcomment',
            name='username',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
