# Generated by Django 3.0.6 on 2020-12-31 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0129_feedcomment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice',
            old_name='subjects',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='practiceenglish',
            old_name='subjects',
            new_name='chapter',
        ),
    ]
