# Generated by Django 3.0.6 on 2021-01-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0130_auto_20201231_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetailsformq',
            name='language',
            field=models.CharField(blank=True, default='None', max_length=500, null=True),
        ),
    ]
