# Generated by Django 3.0.6 on 2021-01-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0131_accountdetailsformq_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaQuizEnglish',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option1', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option2', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option3', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option4', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option5', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('correct', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MegaQuizHindi',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option1', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option2', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option3', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option4', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('option5', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('correct', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
