# Generated by Django 3.0.6 on 2021-01-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0132_megaquizenglish_megaquizhindi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='quetion',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
