# Generated by Django 3.0.6 on 2021-01-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0133_auto_20210104_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceenglish',
            name='option1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practiceenglish',
            name='option2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practiceenglish',
            name='option3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practiceenglish',
            name='option4',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practiceenglish',
            name='option5',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practiceenglish',
            name='quetion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
