# Generated by Django 3.0.6 on 2021-01-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0134_auto_20210105_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceenglish',
            name='option5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
