# Generated by Django 3.0.6 on 2021-01-05 11:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0135_auto_20210105_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceenglish',
            name='quetion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
