# Generated by Django 3.0.6 on 2021-01-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0136_auto_20210105_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('one', models.FileField(blank=True, null=True, upload_to='home/stories', verbose_name='')),
                ('two', models.FileField(blank=True, null=True, upload_to='home/stories', verbose_name='')),
                ('three', models.FileField(blank=True, null=True, upload_to='home/stories', verbose_name='')),
                ('four', models.FileField(blank=True, null=True, upload_to='home/stories', verbose_name='')),
                ('five', models.FileField(blank=True, null=True, upload_to='home/stories', verbose_name='')),
                ('videos', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
