# Generated by Django 3.0.6 on 2021-01-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0137_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='front',
            field=models.FileField(blank=True, null=True, upload_to='home/stories', verbose_name=''),
        ),
        migrations.AddField(
            model_name='stories',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
