# Generated by Django 3.0.6 on 2021-01-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0138_auto_20210106_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
