# Generated by Django 3.0.6 on 2021-01-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0139_feed_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaquizenglish',
            name='time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='megaquizhindi',
            name='time',
            field=models.IntegerField(default=30),
        ),
    ]
