# Generated by Django 3.0.6 on 2021-01-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0140_auto_20210109_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='megaquizresult',
            old_name='score',
            new_name='time1',
        ),
        migrations.RenameField(
            model_name='megaquizresult',
            old_name='time',
            new_name='time2',
        ),
        migrations.RemoveField(
            model_name='megaquizinstruction',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='megaquizresult',
            name='mq',
        ),
        migrations.AddField(
            model_name='megaquizinstruction',
            name='isResultOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='megaquizinstruction',
            name='winner4price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='megaquizinstruction',
            name='winner5price',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='megaquizresult',
            name='day1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='megaquizresult',
            name='day2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='megaquizresult',
            name='day3',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='megaquizresult',
            name='day4',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='megaquizresult',
            name='day5',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='megaquizresult',
            name='day6',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='megaquizresult',
            name='day7',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='megaquizresult',
            name='time3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='megaquizresult',
            name='time4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='megaquizresult',
            name='time5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='megaquizresult',
            name='time6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='megaquizresult',
            name='time7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='megaquizinstruction',
            name='winner1price',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='megaquizinstruction',
            name='winner2price',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='megaquizinstruction',
            name='winner3price',
            field=models.IntegerField(default=2000),
        ),
    ]
