# Generated by Django 3.0.6 on 2021-01-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0141_auto_20210109_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaquizresult',
            name='score',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
