# Generated by Django 3.0.6 on 2021-01-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0142_megaquizresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaquizresult',
            name='time',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
