# Generated by Django 3.0.6 on 2021-01-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0143_megaquizresult_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaquizinstruction',
            name='day',
            field=models.IntegerField(default=20),
        ),
    ]
