# Generated by Django 3.0.6 on 2021-01-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0145_auto_20210110_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megaquizresult',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='megaquizresult',
            name='time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
