# Generated by Django 3.0.6 on 2021-01-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0146_auto_20210110_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaquizinstruction',
            name='isWaitingResult',
            field=models.BooleanField(default=False),
        ),
    ]
