# Generated by Django 3.0.6 on 2021-01-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0147_megaquizinstruction_iswaitingresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceenglish',
            name='quetion',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
