# Generated by Django 3.0.6 on 2021-01-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0148_auto_20210115_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousPaper',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('question', models.FileField(blank=True, null=True, upload_to='home/papers', verbose_name='')),
                ('answer', models.FileField(blank=True, null=True, upload_to='home/papers', verbose_name='')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
