# Generated by Django 3.0.6 on 2021-01-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0149_previouspaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaquizresult',
            name='device',
            field=models.TextField(blank=True, null=True),
        ),
    ]
