# Generated by Django 3.0.6 on 2021-01-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0150_megaquizresult_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaquizenglish',
            name='isForEveryone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='megaquizenglish',
            name='isSpecial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='megaquizhindi',
            name='isForEveryone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='megaquizhindi',
            name='isSpecial',
            field=models.BooleanField(default=False),
        ),
    ]
