# Generated by Django 3.0.6 on 2021-01-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0151_auto_20210128_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetailsformq',
            name='isSpecial',
            field=models.BooleanField(default=False),
        ),
    ]
