# Generated by Django 3.0.6 on 2021-01-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0152_accountdetailsformq_isspecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetailsformq',
            name='questions',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
