# Generated by Django 3.0.6 on 2021-01-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0153_accountdetailsformq_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetailsformq',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
