# Generated by Django 3.0.6 on 2021-01-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0154_accountdetailsformq_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megaquizenglish',
            name='isForEveryone',
        ),
        migrations.RemoveField(
            model_name='megaquizenglish',
            name='isSpecial',
        ),
        migrations.RemoveField(
            model_name='megaquizhindi',
            name='isForEveryone',
        ),
        migrations.RemoveField(
            model_name='megaquizhindi',
            name='isSpecial',
        ),
    ]
