# Generated by Django 3.0.6 on 2021-01-28 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0155_auto_20210128_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('isforAll', models.BooleanField(default=False)),
                ('isforUpdate', models.BooleanField(default=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
