# Generated by Django 3.0.6 on 2021-01-28 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0157_alertrecieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrecieved',
            name='alert',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='home.alert'),
        ),
    ]
