# Generated by Django 3.0.6 on 2021-02-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0159_auto_20210128_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubtreply',
            name='reply',
            field=models.TextField(max_length=10000),
        ),
    ]
