from django.urls import path
from api.views import(
	registration_view,
registration_view1,
	ObtainAuthTokenView,
    categories, categoriesu,
    logout,courses,reghometutor,Createcourse,createdcourses,AddVideo,performance,
    studentquery,AnswerQuery,GetVideo,AddCart,GetCart,GetDetailedCart,checkhreg,RemoveCart,gethomet,buynow,handleRequest,AddToMyCourses,Contactus,Quize,GetFeaturedVideos,AddTest,
    SubmitQuize,GetQuizeResult,AddTest,testall,AddTestCart,RemoveTestCart,GetMyTest,edithometutor,GetMyCourse,GetPaidVideos,geturl,search,getdemo,addwatched,freetest,removeMyTest,newdoubt,fetchdoubts,liked,doubtreply,update,bookmark,replyd,bookmarked,bookmarked,getwallet,wlt,report,megaquizIns,adformq,editadformq,notifyChange,addresults,getresults,GetCtest,addReview,raisenewquery,studentaskquery,generalnotify,getgeneralnotify,getnotes,getfeeds,wordoftheday,acacom,feedlike,feedshare,removefeedlike,removefeedshare,feedcomment,getPractice,newfeed,answer,previousyp,storyviews,alerts

    )
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'api'
urlpatterns = [
    path('register', registration_view, name="register"),
    path('logout', logout, name="logout"),
    path('login', ObtainAuthTokenView.as_view(), name="login"), 
    path('answerquery', AnswerQuery.as_view(), name="answerquery"), 
    path('getvideos', GetVideo.as_view(), name="getvideos"), 
    path('categories', categories, name="categories"), 
    path('categoriesu', categoriesu, name="categoriesu"), 
    path('registerv1', registration_view1, name="registerv1"),
    path('courses', courses, name="courses"), 
    path('reghometutor', reghometutor, name="reghometutors"), 
    path('createcourse', Createcourse.as_view(), name="createcourse"), 
    path('createdcourses', createdcourses, name="createdcourses"), 
    path('addvideo', AddVideo.as_view(), name="addvideo"), 
    path('addcart', AddCart.as_view(), name="addcart"), 
    path('addtestcart', AddTestCart.as_view(), name="addtestcart"), 
    path('getcart', GetCart.as_view(), name="getcart"), 
    path('geturl', geturl, name="geturl"), 
    path('removecart', RemoveCart.as_view(), name="removecart"), 
    path('removetestcart', RemoveTestCart.as_view(), name="removetestcart"), 
    path('getdetailedcart', GetDetailedCart.as_view(), name="getdetailedcart"), 
    path('performance', performance, name="performance"), 
    path('studentquery', studentquery, name="studentquery"),   
    path('checkhreg', checkhreg, name="checkhreg"),   
    path('gethomet', gethomet, name="gethomet"),   
    path('buynow', buynow, name="buynow"),   
    path('handleRequest/',handleRequest,name="handleRequest"),
    path('addtomycourses',AddToMyCourses.as_view(),name="addtomycourses"),
    path('contactus',Contactus.as_view(),name="contactus"),
    path('quize',Quize.as_view(),name="quize"),
    path('submitquize',SubmitQuize.as_view(),name="submitquize"),
    path('getquizeresult',GetQuizeResult.as_view(),name="getquizeresult"),
    path('getmytest',GetMyTest.as_view(),name="getmytest"),
    path('getmycourse',GetMyCourse.as_view(),name="getmycourse"),
    path('getpaidvideos',GetPaidVideos.as_view(),name="getpaidvideos"),
    path('testall',testall,name="testall"),
    path('edithometutor',edithometutor,name="edithometutor"),
    path('getfeturedvideos',GetFeaturedVideos.as_view(),name="getfeturedvideos"),
    path('addtest',AddTest.as_view(),name="addtest"),
    path('search',search,name="search"),
    path('getdemo',getdemo,name="getdemo"),
    path('addwatched',addwatched,name="addwatched"),
    path('freetest',freetest,name="freetest"),
    path('removemytest',removeMyTest,name="removemytest"),
    path('newdoubt',newdoubt,name="newdoubt"), 
    path('fetchdoubts',fetchdoubts,name="fetchdoubts"),
    path('liked',liked,name="liked"),
    path('doubtreply',doubtreply,name="doubtreply"),
    path('update',update,name="update"),
    path('bookmark',bookmark,name="bookmark"), 
    path('bookmarked',bookmarked,name="bookmarked"), 
    path('replyd',replyd,name="replyd"), 
    path('wallet',getwallet,name="wallet"), 
    path('wlt',wlt,name="wlt"),
    path('report',report,name="report"),
    path('megaquizIns',megaquizIns,name="megaquizIns"),
    path('adformq',adformq,name="adformq"),
    path('editadformq',editadformq,name="editadformq"),
    path('notifyChange',notifyChange,name="notifyChange"),
    path('addresults',addresults,name="addresults"),
    path('getresults',getresults,name="getresults"),
    path('getctest',GetCtest.as_view(),name="getctest"),
    path('addReview',addReview,name="addReview"),
    path('raisenewquery',raisenewquery,name="raisenewquery"),
    path('studentaskquery', studentaskquery, name="studentaskquery"),   
    path('generalnotify', generalnotify, name="generalnotify"),   
    path('getgeneralnotify', getgeneralnotify, name="getgeneralnotify"),  
    path('getnotes', getnotes, name="getnotes"),  
    path('getfeeds',getfeeds,name="getfeeds"),
    path('wordoftheday',wordoftheday,name="wordoftheday"),
    path('acacom',acacom,name="acacom"),
    path('feedlike',feedlike,name="feedlike"),
    path('feedshare',feedshare,name="feedshare"),
    path('removefeedshare',removefeedshare,name="removefeedshare"),
    path('removefeedlike',removefeedlike,name="removefeedlike"),
    path('feedcomment',feedcomment,name="feedcomment"),
    path('getPractice',getPractice,name="getPractice"),
    path('newfeed',newfeed,name="newfeed"),
    path('answer',answer,name="answer"),
    path('previousyp',previousyp,name="previousyp"),
    path('storyviews',storyviews,name="storyviews"),
    path('alerts',alerts,name="alerts"),

]

